SR : 
	g++ SenderSR.cpp -lpthread -o SenderSR
	g++ ReceiverSR.cpp -o ReceiverSR
GBN : 
	g++ SenderGBN.cpp -lpthread -o SenderGBN
	g++ ReceiverGBN.cpp -o ReceiverGBN
clean :
	rm -f ReceiverGBN SenderGBN SenderSR ReceiverSR